---
- name: Deploy zabbix agent 
  hosts: mata 
  vars:
    package_ubuntu16: http://repo.zabbix.com/zabbix/3.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.2-1+xenial_all.deb
    package_ubuntu14: http://repo.zabbix.com/zabbix/3.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.2-1+trusty_all.deb 
    zabbix_server_or_proxy: 0.0.0.0
    zabbix_server_or_proxy_port: 10050
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: Install Package for Ubuntu 16.04LTS
    apt: deb={{package_ubuntu16}} state=present
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

  - name: Install Package for Ubuntu 14.04LTS
    apt: deb={{package_ubuntu14}} state=present
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

  - name: Install Zabbix Agent For Your Host
    apt: name=zabbix-agent state=present update_cache=yes 

  - name: Install Zabix Agent conf For Your Host
    template: src=templates/zabbix_agentd.conf  dest=/etc/zabbix/zabbix_proxy.conf
    notify:
    - restart zabbix-agent


  handlers:
  - name: restart zabbix-agent
    service: state=restarted  name=zabbix-agent 

  
